### ISSUE TITLE
Multiple decorators

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldMuseum#14]
We have to find a way to treat multiple decorators, something like

`ArrayManifold{LieGroup{M}}` when both `ArrayManifold` and `LieGroup` are `<:Manifold` but contain the manifold itself internally, too.

I think we should have a `Trait` for that, such that any decorator would also implement "passthrough" variants of their new functions (i.e. the Lie group action). What do you think?

`

**Comment by sdaxen** [comment]
I think since https://github.com/JuliaNLSolvers/ManifoldMuseum/pull/15 was merged, it's okay to close this now.
