### ISSUE TITLE
An idea for “lightweight” manifolds

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldMuseum#2]
One idea is to have manifolds that come without the “overhead” of types points and vectors. I actually like those, but I can understand the urge for easiness of non typed ones, that just accept matrices.
Maybe we could also handle that as a `Trait`? Do we often need to distinguish between those? For example on the sphere the old difference is really whether to set a field value of `x` or just return the array. So one could also call these `ArrayManifolds` then, if we need to distinguish between them.

**Comment by sdaxen** [comment]
One nice feature of types points/vectors is that we can make it explicit what coordinates are being used and dispatch on different coordinate types. But maybe that's not how we want to implement coordinates.

Perhaps for each manifold if a single preferred canonical set of coordinates can be specified, we also have versions of the functions that accept those as inputs and then wrap them in the corresponding point/vector type?

**Comment by kellertuer** [comment]
You're right. For any `Manifold` you could introduce different points and vectors with different coordinate systems (and hence computations of the corresponding functions). Still, for example for `random_point` that would require that the manifold is aware, which coordinates you currently prefer (maybe as a `pointType` field) then.
